---
title: "Process_Sim_2"
format: html
---

```{r}
library(tidyverse)
library(ggdist)
library(ggthemes)
library(tidyquant)
```

```{r}
load("../data/Sim_2.RData")

anyNA(Sim_2)
df_with_na <- Sim_2[apply(is.na(Sim_2), 1, any), ]

cumprod(c(0,0.5,1)) / (cumprod(c(0,0.5,1)) + cumprod(c(1-0.000001,1-0.5,1-0.9999999)))
#therefore
Sim_2$BESc <- ifelse(is.nan(Sim_2$BESc), 1, Sim_2$BESc)
```

```{r}
Sim_2$n_sample <- Sim_2$n_sample*3

# Add indicator or partial
Sim_2$ind_p_all <- ifelse(Sim_2$ind_p1 == 1 & Sim_2$ind_p2 == 1 & Sim_2$ind_p3 == 1, 1, 0)
```

Aggregated dataset
```{r}
Sim_2_agg <- Sim_2 %>%
  group_by(n_sample, c, d) %>%
  summarise(PMP1u_H = mean(PMP1u_H),
            PMP1c_H = mean(PMP1c_H),
            BESc = mean(BESc),
            BESu = mean(BESu))
```

# Lineplot
```{r}
Sim_2_agg %>% ggplot() +
  geom_line(aes(
    x = as.factor(n_sample),
    y = PMP1c_H,
    linetype = "Complete",
    color = as.factor(d),
    group = 1
  )) +
  geom_line(aes(
    x = as.factor(n_sample),
    y = BESc,
    linetype = "BES",
    color = as.factor(d),
    group = 1
  )) +
  scale_linetype_manual(name = "Hypothesis",
                        values = c("Complete" = "solid", "BES" = "longdash")) +
  #geom_hline(yintercept = 8/(8+1), color = "black", linetype = "dotted", alpha = 0.5) +
  labs(x = "Sample Size", y = "Posterior Model Probabilities") +
  ggtitle("Comparison PMPs of BES and complete Hypothesis against the Complement") +
  scale_color_discrete(guide = "none") +
  theme_bw() +
  facet_grid(c ~ d) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
Sim_2_agg %>% ggplot() +
  geom_line(aes(
    x = as.factor(n_sample),
    y = PMP1u_H,
    linetype = "Complete",
    color = as.factor(d),
    group = 1
  )) +
  geom_line(aes(
    x = as.factor(n_sample),
    y = BESu,
    linetype = "BES",
    color = as.factor(d),
    group = 1
  )) +
  scale_linetype_manual(name = "Hypothesis",
                        values = c("Complete" = "solid", "BES" = "longdash")) +
  geom_hline(yintercept = 8/(8+1), color = "black", linetype = "dotted", alpha = 0.5) +
  geom_hline(yintercept = 24/(24+1), color = "grey", linetype = "dotted", alpha = 0.5) +
  labs(x = "Sample Size", y = "Posterior Model Probabilities") +
  ggtitle("Comparison PMPs of BES and complete Hypothesis against the Unconstrained") +
  scale_color_discrete(guide = "none") +
  theme_bw() +
  facet_grid(c ~ d) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


# Complement
```{r}
Sim_2 %>% 
  filter(n_sample %in% c(75, 150, 300, 1500) & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = BESc, fill = factor(ind_comp))) +
  
  geom_boxplot(
    width = 0.12,
    # removing outliers
    outlier.color = NA,
    alpha = 0.5
  ) +
  
  stat_dots(
    # ploting on left side
    side = "right",
    # adjusting position
    justification = 1.2,
    # adjust grouping (binning) of observations
    #binwidth = 0.25
    alpha = 0.2
  ) +
  
  # Themes and Labels
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "Bayesian Evidence Synthesis against Complement",
    x = "Posterior Model Probabilities against Complement",
    y = "",
    fill = "Hypothesis Indicator"
  ) +
  
  facet_wrap(~ n_sample, scales = "free") +
  theme(
    axis.ticks.y = element_blank(), 
    axis.text.y = element_blank())
```
```{r}
Sim_2 %>% 
  filter(n_sample %in% c(75, 150, 300, 1500) & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = PMP1c_H, fill = factor(ind_p_all))) +
  
  geom_boxplot(
    width = 0.12,
    # removing outliers
    outlier.color = NA,
    alpha = 0.5
  ) +
  
  stat_dots(
    # ploting on left side
    side = "right",
    # adjusting position
    justification = 1.2,
    # adjust grouping (binning) of observations
    #binwidth = 0.25
    alpha = 0.2
  ) +
  
  # Themes and Labels
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "PMPs against complement",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  
  facet_wrap(~ n_sample, scales = "free") +
  theme(
    axis.ticks.y = element_blank(), 
    axis.text.y = element_blank())
```



# Unconstrained
```{r}
Sim_2 %>% 
  filter(n_sample %in% c(75, 150, 300, 1500) & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = BESu, fill = factor(ind_comp))) +
  
  geom_boxplot(
    width = 0.12,
    # removing outliers
    outlier.color = NA,
    alpha = 0.5
  ) +
  
  stat_dots(
    # ploting on left side
    side = "right",
    # adjusting position
    justification = 1.2,
    # adjust grouping (binning) of observations
    #binwidth = 0.25
    alpha = 0.2
  ) +
  
  # Themes and Labels
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "Bayesian Evidence Synthesis against Unconstrained",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  
  facet_wrap(~ n_sample, scales = "free") +
  theme(
    axis.ticks.y = element_blank(), 
    axis.text.y = element_blank())
```

```{r}
Sim_2 %>% 
  filter(n_sample %in% c(75, 150, 300, 1500) & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = PMP1u_H, fill = factor(ind_p_all))) +
  
  geom_boxplot(
    width = 0.12,
    # removing outliers
    outlier.color = NA,
    alpha = 0.5
  ) +
  
  stat_dots(
    # ploting on left side
    side = "right",
    # adjusting position
    justification = 1.2,
    # adjust grouping (binning) of observations
    #binwidth = 0.25
    alpha = 0.2
  ) +
  
  # Themes and Labels
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "PMPs against Unconstrained",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  
  facet_wrap(~ n_sample, scales = "free") +
  theme(
    axis.ticks.y = element_blank(), 
    axis.text.y = element_blank())
```













# Example better 

## Unconstrained
```{r}
# Compute the common x-axis limits
x_min <- min(Sim_2$PMP1u_H, Sim_2$BESu, na.rm = TRUE)
x_max <- max(Sim_2$PMP1u_H, Sim_2$BESu, na.rm = TRUE)

# Update p1 and p2 to use the same x-axis scale
p1 <- Sim_2 %>% 
  filter(n_sample == 75 & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = PMP1u_H, fill = factor(ind_p_all))) +
  geom_boxplot(width = 0.12, outlier.color = NA, alpha = 0.5) +
  stat_dots(side = "right", justification = 1.2, alpha = 0.2) +
  scale_x_continuous(limits = c(x_min, x_max)) +  # Ensure same scale
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "PMPs against Unconstrained",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  facet_wrap(~ n_sample) +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank())

p2 <- Sim_2 %>% 
  filter(n_sample == 75 & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = BESu, fill = factor(ind_comp))) +
  geom_boxplot(width = 0.12, outlier.color = NA, alpha = 0.5) +
  stat_dots(side = "right", justification = 1.2, alpha = 0.2) +
  scale_x_continuous(limits = c(x_min, x_max)) +  # Ensure same scale
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "Bayesian Evidence Synthesis against Unconstrained",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  facet_wrap(~ n_sample) +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank())

```

```{r}
gridExtra::grid.arrange(p1, p2, nrow = 1)
```

```{r}
# Compute the common x-axis limits
x_min <- min(Sim_2$PMP1u_H, Sim_2$BESu, na.rm = TRUE)
x_max <- max(Sim_2$PMP1u_H, Sim_2$BESu, na.rm = TRUE)

# Update p1 and p2 to use the same x-axis scale
p1 <- Sim_2 %>% 
  filter(n_sample == 150 & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = PMP1u_H, fill = factor(ind_p_all))) +
  geom_boxplot(width = 0.12, outlier.color = NA, alpha = 0.5) +
  stat_dots(side = "right", justification = 1.2, alpha = 0.2) +
  scale_x_continuous(limits = c(x_min, x_max)) +  # Ensure same scale
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "PMPs against Unconstrained",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  facet_wrap(~ n_sample) +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank())

p2 <- Sim_2 %>% 
  filter(n_sample == 150 & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = BESu, fill = factor(ind_comp))) +
  geom_boxplot(width = 0.12, outlier.color = NA, alpha = 0.5) +
  stat_dots(side = "right", justification = 1.2, alpha = 0.2) +
  scale_x_continuous(limits = c(x_min, x_max)) +  # Ensure same scale
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "Bayesian Evidence Synthesis against Unconstrained",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  facet_wrap(~ n_sample) +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank())

```

```{r}
gridExtra::grid.arrange(p1, p2, nrow = 1)
```

```{r}
# Compute the common x-axis limits
x_min <- min(Sim_2$PMP1u_H, Sim_2$BESu, na.rm = TRUE)
x_max <- max(Sim_2$PMP1u_H, Sim_2$BESu, na.rm = TRUE)

# Update p1 and p2 to use the same x-axis scale
p1 <- Sim_2 %>% 
  filter(n_sample == 300 & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = PMP1u_H, fill = factor(ind_p_all))) +
  geom_boxplot(width = 0.12, outlier.color = NA, alpha = 0.5) +
  stat_dots(side = "right", justification = 1.2, alpha = 0.2) +
  scale_x_continuous(limits = c(x_min, x_max)) +  # Ensure same scale
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "PMPs against Unconstrained",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  facet_wrap(~ n_sample) +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank())

p2 <- Sim_2 %>% 
  filter(n_sample == 300 & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = BESu, fill = factor(ind_comp))) +
  geom_boxplot(width = 0.12, outlier.color = NA, alpha = 0.5) +
  stat_dots(side = "right", justification = 1.2, alpha = 0.2) +
  scale_x_continuous(limits = c(x_min, x_max)) +  # Ensure same scale
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "Bayesian Evidence Synthesis against Unconstrained",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  facet_wrap(~ n_sample) +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank())

```

```{r}
gridExtra::grid.arrange(p1, p2, nrow = 1)
```


## Complement


```{r}
# Compute the common x-axis limits
x_min <- min(Sim_2$PMP1c_H, Sim_2$BESc, na.rm = TRUE)
x_max <- max(Sim_2$PMP1c_H, Sim_2$BESc, na.rm = TRUE)

# Update p1 and p2 to use the same x-axis scale
p1 <- Sim_2 %>% 
  filter(n_sample == 75 & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = PMP1c_H, fill = factor(ind_p_all))) +
  geom_boxplot(width = 0.12, outlier.color = NA, alpha = 0.5) +
  stat_dots(side = "right", justification = 1.2, alpha = 0.2) +
  scale_x_continuous(limits = c(x_min, x_max)) +  # Ensure same scale
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "PMPs against Complement",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  facet_wrap(~ n_sample) +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank())

p2 <- Sim_2 %>% 
  filter(n_sample == 75 & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = BESc, fill = factor(ind_comp))) +
  geom_boxplot(width = 0.12, outlier.color = NA, alpha = 0.5) +
  stat_dots(side = "right", justification = 1.2, alpha = 0.2) +
  scale_x_continuous(limits = c(x_min, x_max)) +  # Ensure same scale
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "Bayesian Evidence Synthesis against Complement",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  facet_wrap(~ n_sample) +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank())

```

```{r}
gridExtra::grid.arrange(p1, p2, nrow = 1)
```

```{r}
# Compute the common x-axis limits
x_min <- min(Sim_2$PMP1c_H, Sim_2$BESc, na.rm = TRUE)
x_max <- max(Sim_2$PMP1c_H, Sim_2$BESc, na.rm = TRUE)

# Update p1 and p2 to use the same x-axis scale
p1 <- Sim_2 %>% 
  filter(n_sample == 150 & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = PMP1c_H, fill = factor(ind_p_all))) +
  geom_boxplot(width = 0.12, outlier.color = NA, alpha = 0.5) +
  stat_dots(side = "right", justification = 1.2, alpha = 0.2) +
  scale_x_continuous(limits = c(x_min, x_max)) +  # Ensure same scale
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "PMPs against Complement",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  facet_wrap(~ n_sample) +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank())

p2 <- Sim_2 %>% 
  filter(n_sample == 150 & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = BESc, fill = factor(ind_comp))) +
  geom_boxplot(width = 0.12, outlier.color = NA, alpha = 0.5) +
  stat_dots(side = "right", justification = 1.2, alpha = 0.2) +
  scale_x_continuous(limits = c(x_min, x_max)) +  # Ensure same scale
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "Bayesian Evidence Synthesis against Complement",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  facet_wrap(~ n_sample) +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank())

```

```{r}
gridExtra::grid.arrange(p1, p2, nrow = 1)
```

```{r}
# Compute the common x-axis limits
x_min <- min(Sim_2$PMP1c_H, Sim_2$BESc, na.rm = TRUE)
x_max <- max(Sim_2$PMP1c_H, Sim_2$BESc, na.rm = TRUE)

# Update p1 and p2 to use the same x-axis scale
p1 <- Sim_2 %>% 
  filter(n_sample == 300 & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = PMP1c_H, fill = factor(ind_p_all))) +
  geom_boxplot(width = 0.12, outlier.color = NA, alpha = 0.5) +
  stat_dots(side = "right", justification = 1.2, alpha = 0.2) +
  scale_x_continuous(limits = c(x_min, x_max)) +  # Ensure same scale
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "PMPs against Complement",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  facet_wrap(~ n_sample) +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank())

p2 <- Sim_2 %>% 
  filter(n_sample == 300 & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = BESc, fill = factor(ind_comp))) +
  geom_boxplot(width = 0.12, outlier.color = NA, alpha = 0.5) +
  stat_dots(side = "right", justification = 1.2, alpha = 0.2) +
  scale_x_continuous(limits = c(x_min, x_max)) +  # Ensure same scale
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "Bayesian Evidence Synthesis against Complement",
    x = "Posterior Model Probabilities",
    y = "Sample Size",
    fill = "Hypothesis Indicator"
  ) +
  facet_wrap(~ n_sample) +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank())

```

```{r}
gridExtra::grid.arrange(p1, p2, nrow = 1)
```





















#######################
#old fun
```{r}
Sim_2 %>% 
  filter(n_sample %in% c(75, 150, 300, 1500) & c == 0.2 & d == 0.2) %>%
  ggplot(aes(y = factor(n_sample), x = BESu, fill = factor(ind_comp))) +
  
  geom_boxplot(
    width = 0.12,
    # removing outliers
    outlier.color = NA,
    alpha = 0.5
  ) +
  
  stat_dots(
    # ploting on left side
    side = "right",
    # adjusting position
    justification = 1.2,
    # adjust grouping (binning) of observations
    #binwidth = 0.25
    alpha = 0.2
  ) +
  
  # Themes and Labels
  scale_fill_tq() +
  theme_tq() +
  labs(
    title = "Bayesian Evidence Synthesis against Complement",
    x = "Posterior Model Probabilities against Complement",
    y = "",
    fill = "Hypothesis Indicator"
  ) +
  
  facet_wrap(~ n_sample, scales = "free") +
  theme(
    axis.ticks.y = element_blank(), 
    axis.text.y = element_blank())
```

```{r}
Sim_2 %>% 
  filter(n_sample %in% c(75) & c == 0.2 & d == 0.2) %>%
  ggplot(aes(x = BESu, fill = factor(ind_p_all), color = factor(ind_p_all))) +
  
  stat_dots(
    aes(y = 0),
    side = "top",
    scale = 0.8,
    alpha = 0.6,
    dotsize = 1.5
  ) +
  
  geom_boxplot(
    aes(y = -0.15),
    width = 0.05,
    outlier.shape = 16,
    outlier.size = 1,
    alpha = 0.7
  ) +
  
  #facet_wrap(~ n_sample, ncol = 2, labeller = label_both, scales="free") +
  
  scale_fill_tq() +
  scale_color_tq() +
  theme_tq() +
  labs(
    title = paste("PMPs against complement, n =",n, "c =",c, "d =",d),
    x = "Posterior Model Probabilities",
    y = "",
    fill = "Hypothesis Indicator",
    color = "Hypothesis Indicator"
  ) +
  theme(
    strip.text = element_text(size = 11, face = "bold"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )
```

